
export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    inventory: "Inventory",
    sales: "Sales",
    customers: "Customers",
    expenses: "Expenses",
    reports: "Reports",
    settings: "Settings",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    welcome: "Welcome back",
    total_sales: "Total Sales",
    total_inventory: "Total Items",
    total_customers: "Total Customers",
    total_expenses: "Total Expenses",
    total_categories: "Total Categories",
    add_product: "Add Product",
    add_sale: "Add Sale",
    add_expense: "Add Expense",
    add_customer: "Add Customer",
    demo_data: "Demo Data",
    load_demo: "Load Demo Data",
    clear_demo: "Clear All Data",
    ai_placeholder: "Ask anything about your business...",
    no_data: "No data available",
    recent_sales: "Recent Sales",
    low_stock: "Low Stock Alert",
    name: "Name",
    quantity: "Quantity",
    price: "Price",
    date: "Date",
    amount: "Amount",
    status: "Status",
    save: "Save",
    cancel: "Cancel",
    search: "Search...",
    profit_loss: "Profit & Loss",
    language_toggle: "বাংলা",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    inventory: "ইনভেন্টরি",
    sales: "বিক্রয়",
    customers: "গ্রাহক",
    expenses: "ব্যয়",
    reports: "প্রতিবেদন",
    settings: "সেটিংস",
    login: "লগইন",
    signup: "সাইন আপ",
    logout: "লগআউট",
    welcome: "স্বাগতম",
    total_sales: "মোট বিক্রয়",
    total_inventory: "মোট পণ্য",
    total_customers: "মোট গ্রাহক",
    total_expenses: "মোট ব্যয়",
    total_categories: "মোট ক্যাটাগরি",
    add_product: "পণ্য যোগ করুন",
    add_sale: "বিক্রয় যোগ করুন",
    add_expense: "ব্যয় যোগ করুন",
    add_customer: "গ্রাহক যোগ করুন",
    demo_data: "ডেমো ডেটা",
    load_demo: "ডেমো ডেটা লোড করুন",
    clear_demo: "সব ডেটা মুছুন",
    ai_placeholder: "আপনার ব্যবসা সম্পর্কে জিজ্ঞাসা করুন...",
    no_data: "কোন তথ্য নেই",
    recent_sales: "সাম্প্রতিক বিক্রয়",
    low_stock: "কম স্টক সতর্কবার্তা",
    name: "নাম",
    quantity: "পরিমাণ",
    price: "মূল্য",
    date: "তারিখ",
    amount: "পরিমাণ",
    status: "অবস্থা",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল করুন",
    search: "খুঁজুন...",
    profit_loss: "লাভ ও ক্ষতি",
    language_toggle: "English",
  }
};

export const PRODUCT_CATEGORIES = [
  "Grocery & Grains",
  "Grocery As Gift",
  "Homemade Pickle",
  "Homemade Spices",
  "Honey, Nuts & Seeds",
  "Mashik Shodai",
  "Oil & Extracts",
  "Others Product",
  "Package",
  "shop",
  "Tea Lovers"
];

export const DEMO_DATA = {
  inventory: [
    { id: '1', name: 'Fresh Milk 1L', sku: 'MLK-001', price: 80, cost: 65, quantity: 24, category: 'Grocery & Grains' },
    { id: '2', name: 'Premium Tea 500g', sku: 'TEA-002', price: 450, cost: 380, quantity: 5, category: 'Tea Lovers' },
    { id: '3', name: 'ACI Salt 1kg', sku: 'SLT-003', price: 40, cost: 32, quantity: 50, category: 'Grocery & Grains' },
  ],
  sales: [
    { id: 's1', date: '2023-10-01', customerName: 'Rahim Ali', items: [], totalAmount: 1200 },
    { id: 's2', date: '2023-10-02', customerName: 'Karim Uddin', items: [], totalAmount: 850 },
  ],
  customers: [
    { id: 'c1', name: 'Rahim Ali', phone: '01711111111', email: 'rahim@test.com', totalSpent: 5000 },
    { id: 'c2', name: 'Karim Uddin', phone: '01822222222', email: 'karim@test.com', totalSpent: 3400 },
  ],
  expenses: [
    { id: 'e1', date: '2023-10-01', description: 'Electricity Bill', category: 'Utility', amount: 2500 },
    { id: 'e2', date: '2023-10-05', description: 'Shop Rent', category: 'Rent', amount: 15000 },
  ]
};
